import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import NewsItem from "@/components/NewsItem/NewsItem";

export interface StoriesProps {
  author: string;
  comment_text: null | string;
  created_at: string;
  created_at_i: number;
  num_comments: number;
  objectID: string;
  parent_id: null | string;
  points: number;
  story_id: null | string;
  story_text: null | string;
  story_title: null | string;
  story_url: null | string;
  title: string;
  url: string;
  _highlightResult: {};
  _tags: {};
}

export const getStaticProps: GetStaticProps<{ posts: StoriesProps[] }> = async (
  context
) => {
  const res = await fetch(
    "http://hn.algolia.com/api/v1//search?query=foo&tags=story&page=1"
  );
  const posts: StoriesProps[] = await res.json().then((res) => res.hits);
  if (!posts) {
    return {
      notFound: true,
    };
  }
  return {
    props: {
      posts,
    },
  };
};

export default function Home({ posts }: { posts: StoriesProps[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.wrapper}>
          <ul className={styles.list}>
            {posts.map((story: StoriesProps) => {
              return <NewsItem key={story.objectID} story={story} />;
            })}
          </ul>
        </div>
      </main>
    </>
  );
}
